[tool.poetry]
name = "checkio1"
version = "0.1.0"
description = "This project converts a blurred image with low resolution to a high-resolution image to use as a wallpaper for my project."
authors = ["Hussein Tarhini <husseintarhini168@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Pillow = "^9.0"          
numpy = "^1.21"          
matplotlib = "^3.5"     

# Development dependencies
[tool.poetry.dev-dependencies]
pytest = "^7.0"      
pylint = "^2.14"      
black = "^22.3"      
pandas = "^1.3" 
coverage = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
